title: My life is not interesting enough for a captivating blog
author: Amber Besseling
email: noneofyourbusiness@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Well, I could tell you my life story but I think my Stephen King-esque dreams would be much more entertaining.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
